include:
  - project: "ci/templates"
    file: "docker/build-image-template.yml"
  - project: "ci/templates"
    file: "semantic-release-template.yml"
  - project: "ci/templates"
    file: "badges/badges-template.yml"
  - project: "ci/templates"
    file: "security/trivy-template.yml"

stages:
  - lint
  - build
  - test
  - release
  - badges

lint:
  image: golangci/golangci-lint:v1.50.1-alpine
  stage: lint
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/
  script:
    - golangci-lint run -v

test:
  image: golang:1.19.3
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/) -v -cover
  coverage: '/coverage: \d+.\d+% of statements/'
