GO_GOLANGCI_LINT_CLI_LINT_MODE: project
GO_GOLANGCI_LINT_ARGUMENTS: --timeout 10m
GO_REVIVE_ARGUMENTS: -formatter friendly -config .revive.toml
REPOSITORY_KICS_ARGUMENTS: --exclude-paths dev --fail-on high
