app:
  name: gics-to-kafka
  log-level: info
  http:
    auth:
      user:
      password:
    port: 8080

gics:
  signer-id: "Patienten-ID"

kafka:
  bootstrap-servers: localhost:9092
  security-protocol: ssl
  ssl:
    ca-location: /app/cert/kafka-ca.pem
    certificate-location: /app/cert/app-cert.pem
    key-location: /app/cert/app-key.pem
    key-password: private-key-password
  output-topic: gics-notification
