name: Go

on:
  push:
#    branches: [ $default-branch ]
  pull_request:
#    branches: [ $default-branch ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v ./...

      - name: update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: 'true'
          chart: 'true'
          amend: 'false'
        if: |
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'push'
        continue-on-error: true
